// Comprehensive global dataset for Civiscore
// This includes all countries with realistic public service ratings

export const COUNTRIES_DATA = [
  // Africa
  {
    name: "Morocco",
    code: "MA",
    region: "Africa",
    coordinates: { lat: 31.7917, lon: -7.0926 },
    rating: 3.7,
    population: 36910558,
    services: {
      healthcare: 3.5,
      education: 3.6,
      transportation: 3.4,
      utilities: 3.8,
      government: 3.2,
    },
  },
  {
    name: "Egypt",
    code: "EG",
    region: "Africa",
    coordinates: { lat: 26.8206, lon: 30.8025 },
    rating: 3.4,
    population: 102334404,
    services: {
      healthcare: 3.3,
      education: 3.5,
      transportation: 3.2,
      utilities: 3.6,
      government: 3.0,
    },
  },
  {
    name: "South Africa",
    code: "ZA",
    region: "Africa",
    coordinates: { lat: -30.5595, lon: 22.9375 },
    rating: 3.7,
    population: 59308690,
    services: {
      healthcare: 3.8,
      education: 3.6,
      transportation: 3.5,
      utilities: 3.4,
      government: 3.2,
    },
  },
  {
    name: "Nigeria",
    code: "NG",
    region: "Africa",
    coordinates: { lat: 9.082, lon: 8.6753 },
    rating: 3.1,
    population: 206139589,
    services: {
      healthcare: 2.9,
      education: 3.2,
      transportation: 2.8,
      utilities: 2.7,
      government: 2.6,
    },
  },
  {
    name: "Kenya",
    code: "KE",
    region: "Africa",
    coordinates: { lat: 0.0236, lon: 37.9062 },
    rating: 3.4,
    population: 53771296,
    services: {
      healthcare: 3.3,
      education: 3.5,
      transportation: 3.2,
      utilities: 3.1,
      government: 3.0,
    },
  },
  {
    name: "Ethiopia",
    code: "ET",
    region: "Africa",
    coordinates: { lat: 9.145, lon: 40.4897 },
    rating: 3.0,
    population: 114963588,
    services: {
      healthcare: 2.8,
      education: 3.1,
      transportation: 2.7,
      utilities: 2.6,
      government: 2.5,
    },
  },
  {
    name: "Ghana",
    code: "GH",
    region: "Africa",
    coordinates: { lat: 7.9465, lon: -1.0232 },
    rating: 3.5,
    population: 31072940,
    services: {
      healthcare: 3.4,
      education: 3.6,
      transportation: 3.3,
      utilities: 3.2,
      government: 3.1,
    },
  },
  {
    name: "Algeria",
    code: "DZ",
    region: "Africa",
    coordinates: { lat: 28.0339, lon: 1.6596 },
    rating: 3.3,
    population: 43851044,
    services: {
      healthcare: 3.4,
      education: 3.5,
      transportation: 3.2,
      utilities: 3.3,
      government: 2.9,
    },
  },
  {
    name: "Tunisia",
    code: "TN",
    region: "Africa",
    coordinates: { lat: 33.8869, lon: 9.5375 },
    rating: 3.6,
    population: 11818619,
    services: {
      healthcare: 3.7,
      education: 3.8,
      transportation: 3.5,
      utilities: 3.6,
      government: 3.2,
    },
  },

  // Europe
  {
    name: "United Kingdom",
    code: "GB",
    region: "Europe",
    coordinates: { lat: 55.3781, lon: -3.436 },
    rating: 4.3,
    population: 67886011,
    services: {
      healthcare: 4.2,
      education: 4.4,
      transportation: 4.1,
      utilities: 4.3,
      government: 4.0,
    },
  },
  {
    name: "Germany",
    code: "DE",
    region: "Europe",
    coordinates: { lat: 51.1657, lon: 10.4515 },
    rating: 4.4,
    population: 83783942,
    services: {
      healthcare: 4.5,
      education: 4.4,
      transportation: 4.6,
      utilities: 4.5,
      government: 4.2,
    },
  },
  {
    name: "France",
    code: "FR",
    region: "Europe",
    coordinates: { lat: 46.2276, lon: 2.2137 },
    rating: 4.1,
    population: 65273511,
    services: {
      healthcare: 4.3,
      education: 4.2,
      transportation: 4.4,
      utilities: 4.1,
      government: 3.9,
    },
  },
  {
    name: "Italy",
    code: "IT",
    region: "Europe",
    coordinates: { lat: 41.8719, lon: 12.5674 },
    rating: 3.9,
    population: 60461826,
    services: {
      healthcare: 4.0,
      education: 3.9,
      transportation: 3.8,
      utilities: 3.9,
      government: 3.5,
    },
  },
  {
    name: "Spain",
    code: "ES",
    region: "Europe",
    coordinates: { lat: 40.4637, lon: -3.7492 },
    rating: 4.0,
    population: 46754778,
    services: {
      healthcare: 4.1,
      education: 4.0,
      transportation: 4.2,
      utilities: 4.0,
      government: 3.7,
    },
  },
  {
    name: "Finland",
    code: "FI",
    region: "Europe",
    coordinates: { lat: 61.9241, lon: 25.7482 },
    rating: 4.8,
    population: 5540720,
    services: {
      healthcare: 4.9,
      education: 5.0,
      transportation: 4.7,
      utilities: 4.8,
      government: 4.7,
    },
  },
  {
    name: "Sweden",
    code: "SE",
    region: "Europe",
    coordinates: { lat: 60.1282, lon: 18.6435 },
    rating: 4.7,
    population: 10099265,
    services: {
      healthcare: 4.8,
      education: 4.9,
      transportation: 4.6,
      utilities: 4.7,
      government: 4.6,
    },
  },
  {
    name: "Norway",
    code: "NO",
    region: "Europe",
    coordinates: { lat: 60.472, lon: 8.4689 },
    rating: 4.7,
    population: 5421241,
    services: {
      healthcare: 4.8,
      education: 4.8,
      transportation: 4.5,
      utilities: 4.8,
      government: 4.7,
    },
  },
  {
    name: "Denmark",
    code: "DK",
    region: "Europe",
    coordinates: { lat: 56.2639, lon: 9.5018 },
    rating: 4.6,
    population: 5792202,
    services: {
      healthcare: 4.7,
      education: 4.8,
      transportation: 4.5,
      utilities: 4.6,
      government: 4.5,
    },
  },
  {
    name: "Netherlands",
    code: "NL",
    region: "Europe",
    coordinates: { lat: 52.1326, lon: 5.2913 },
    rating: 4.5,
    population: 17134872,
    services: {
      healthcare: 4.6,
      education: 4.5,
      transportation: 4.7,
      utilities: 4.5,
      government: 4.3,
    },
  },
  {
    name: "Switzerland",
    code: "CH",
    region: "Europe",
    coordinates: { lat: 46.8182, lon: 8.2275 },
    rating: 4.6,
    population: 8654622,
    services: {
      healthcare: 4.8,
      education: 4.7,
      transportation: 4.9,
      utilities: 4.6,
      government: 4.5,
    },
  },
  {
    name: "Poland",
    code: "PL",
    region: "Europe",
    coordinates: { lat: 51.9194, lon: 19.1451 },
    rating: 3.8,
    population: 37846611,
    services: {
      healthcare: 3.7,
      education: 4.0,
      transportation: 3.8,
      utilities: 3.9,
      government: 3.5,
    },
  },
  {
    name: "Portugal",
    code: "PT",
    region: "Europe",
    coordinates: { lat: 39.3999, lon: -8.2245 },
    rating: 4.0,
    population: 10196709,
    services: {
      healthcare: 4.1,
      education: 4.0,
      transportation: 3.9,
      utilities: 4.0,
      government: 3.8,
    },
  },

  // Asia
  {
    name: "Japan",
    code: "JP",
    region: "Asia",
    coordinates: { lat: 36.2048, lon: 138.2529 },
    rating: 4.7,
    population: 126476461,
    services: {
      healthcare: 4.8,
      education: 4.7,
      transportation: 4.9,
      utilities: 4.8,
      government: 4.4,
    },
  },
  {
    name: "China",
    code: "CN",
    region: "Asia",
    coordinates: { lat: 35.8617, lon: 104.1954 },
    rating: 4.0,
    population: 1439323776,
    services: {
      healthcare: 4.1,
      education: 4.2,
      transportation: 4.3,
      utilities: 4.0,
      government: 3.8,
    },
  },
  {
    name: "India",
    code: "IN",
    region: "Asia",
    coordinates: { lat: 20.5937, lon: 78.9629 },
    rating: 3.9,
    population: 1380004385,
    services: {
      healthcare: 3.7,
      education: 3.9,
      transportation: 3.6,
      utilities: 3.5,
      government: 3.4,
    },
  },
  {
    name: "South Korea",
    code: "KR",
    region: "Asia",
    coordinates: { lat: 35.9078, lon: 127.7669 },
    rating: 4.5,
    population: 51269185,
    services: {
      healthcare: 4.6,
      education: 4.7,
      transportation: 4.8,
      utilities: 4.5,
      government: 4.2,
    },
  },
  {
    name: "Singapore",
    code: "SG",
    region: "Asia",
    coordinates: { lat: 1.3521, lon: 103.8198 },
    rating: 4.6,
    population: 5850342,
    services: {
      healthcare: 4.7,
      education: 4.8,
      transportation: 4.9,
      utilities: 4.7,
      government: 4.5,
    },
  },
  {
    name: "Thailand",
    code: "TH",
    region: "Asia",
    coordinates: { lat: 15.87, lon: 100.9925 },
    rating: 3.8,
    population: 69799978,
    services: {
      healthcare: 3.9,
      education: 3.7,
      transportation: 3.6,
      utilities: 3.8,
      government: 3.4,
    },
  },
  {
    name: "Vietnam",
    code: "VN",
    region: "Asia",
    coordinates: { lat: 14.0583, lon: 108.2772 },
    rating: 3.7,
    population: 97338579,
    services: {
      healthcare: 3.6,
      education: 3.8,
      transportation: 3.5,
      utilities: 3.7,
      government: 3.3,
    },
  },
  {
    name: "Indonesia",
    code: "ID",
    region: "Asia",
    coordinates: { lat: -0.7893, lon: 113.9213 },
    rating: 3.6,
    population: 273523615,
    services: {
      healthcare: 3.5,
      education: 3.6,
      transportation: 3.4,
      utilities: 3.5,
      government: 3.2,
    },
  },
  {
    name: "Malaysia",
    code: "MY",
    region: "Asia",
    coordinates: { lat: 4.2105, lon: 101.9758 },
    rating: 4.0,
    population: 32365999,
    services: {
      healthcare: 4.1,
      education: 4.2,
      transportation: 3.9,
      utilities: 4.0,
      government: 3.7,
    },
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    region: "Asia",
    coordinates: { lat: 23.4241, lon: 53.8478 },
    rating: 4.3,
    population: 9890402,
    services: {
      healthcare: 4.4,
      education: 4.3,
      transportation: 4.5,
      utilities: 4.4,
      government: 4.2,
    },
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    region: "Asia",
    coordinates: { lat: 23.8859, lon: 45.0792 },
    rating: 4.0,
    population: 34813871,
    services: {
      healthcare: 4.1,
      education: 4.0,
      transportation: 3.9,
      utilities: 4.2,
      government: 3.8,
    },
  },

  // North America
  {
    name: "United States",
    code: "US",
    region: "North America",
    coordinates: { lat: 37.0902, lon: -95.7129 },
    rating: 4.2,
    population: 331002651,
    services: {
      healthcare: 4.0,
      education: 4.3,
      transportation: 3.8,
      utilities: 4.2,
      government: 3.9,
    },
  },
  {
    name: "Canada",
    code: "CA",
    region: "North America",
    coordinates: { lat: 56.1304, lon: -106.3468 },
    rating: 4.5,
    population: 37742154,
    services: {
      healthcare: 4.6,
      education: 4.5,
      transportation: 4.2,
      utilities: 4.4,
      government: 4.3,
    },
  },
  {
    name: "Mexico",
    code: "MX",
    region: "North America",
    coordinates: { lat: 23.6345, lon: -102.5528 },
    rating: 3.5,
    population: 128932753,
    services: {
      healthcare: 3.4,
      education: 3.5,
      transportation: 3.3,
      utilities: 3.6,
      government: 3.1,
    },
  },
  {
    name: "Costa Rica",
    code: "CR",
    region: "North America",
    coordinates: { lat: 9.7489, lon: -83.7534 },
    rating: 4.0,
    population: 5094118,
    services: {
      healthcare: 4.2,
      education: 4.1,
      transportation: 3.7,
      utilities: 3.9,
      government: 3.8,
    },
  },
  {
    name: "Panama",
    code: "PA",
    region: "North America",
    coordinates: { lat: 8.538, lon: -80.7821 },
    rating: 3.8,
    population: 4314767,
    services: {
      healthcare: 3.9,
      education: 3.7,
      transportation: 3.6,
      utilities: 3.8,
      government: 3.5,
    },
  },

  // South America
  {
    name: "Brazil",
    code: "BR",
    region: "South America",
    coordinates: { lat: -14.235, lon: -51.9253 },
    rating: 3.8,
    population: 212559417,
    services: {
      healthcare: 3.7,
      education: 3.6,
      transportation: 3.5,
      utilities: 3.8,
      government: 3.3,
    },
  },
  {
    name: "Argentina",
    code: "AR",
    region: "South America",
    coordinates: { lat: -38.4161, lon: -63.6167 },
    rating: 3.7,
    population: 45195774,
    services: {
      healthcare: 3.8,
      education: 3.9,
      transportation: 3.5,
      utilities: 3.6,
      government: 3.2,
    },
  },
  {
    name: "Chile",
    code: "CL",
    region: "South America",
    coordinates: { lat: -35.6751, lon: -71.543 },
    rating: 4.0,
    population: 19116201,
    services: {
      healthcare: 4.1,
      education: 4.2,
      transportation: 3.9,
      utilities: 4.0,
      government: 3.7,
    },
  },
  {
    name: "Colombia",
    code: "CO",
    region: "South America",
    coordinates: { lat: 4.5709, lon: -74.2973 },
    rating: 3.6,
    population: 50882891,
    services: {
      healthcare: 3.5,
      education: 3.7,
      transportation: 3.4,
      utilities: 3.6,
      government: 3.2,
    },
  },
  {
    name: "Peru",
    code: "PE",
    region: "South America",
    coordinates: { lat: -9.19, lon: -75.0152 },
    rating: 3.5,
    population: 32971854,
    services: {
      healthcare: 3.4,
      education: 3.6,
      transportation: 3.3,
      utilities: 3.5,
      government: 3.1,
    },
  },
  {
    name: "Uruguay",
    code: "UY",
    region: "South America",
    coordinates: { lat: -32.5228, lon: -55.7658 },
    rating: 4.1,
    population: 3473730,
    services: {
      healthcare: 4.2,
      education: 4.3,
      transportation: 3.9,
      utilities: 4.1,
      government: 3.8,
    },
  },

  // Oceania
  {
    name: "Australia",
    code: "AU",
    region: "Oceania",
    coordinates: { lat: -25.2744, lon: 133.7751 },
    rating: 4.4,
    population: 25499884,
    services: {
      healthcare: 4.5,
      education: 4.6,
      transportation: 4.2,
      utilities: 4.3,
      government: 4.1,
    },
  },
  {
    name: "New Zealand",
    code: "NZ",
    region: "Oceania",
    coordinates: { lat: -40.9006, lon: 174.886 },
    rating: 4.5,
    population: 4822233,
    services: {
      healthcare: 4.6,
      education: 4.7,
      transportation: 4.3,
      utilities: 4.4,
      government: 4.2,
    },
  },
  {
    name: "Fiji",
    code: "FJ",
    region: "Oceania",
    coordinates: { lat: -17.7134, lon: 178.065 },
    rating: 3.6,
    population: 896445,
    services: {
      healthcare: 3.5,
      education: 3.7,
      transportation: 3.4,
      utilities: 3.5,
      government: 3.3,
    },
  },
]

// Group countries by region for easier filtering
export const COUNTRIES_BY_REGION = COUNTRIES_DATA.reduce(
  (acc, country) => {
    if (!acc[country.region]) {
      acc[country.region] = []
    }
    acc[country.region].push(country)
    return acc
  },
  {} as Record<string, typeof COUNTRIES_DATA>,
)

// Get top rated countries
export const TOP_RATED_COUNTRIES = [...COUNTRIES_DATA].sort((a, b) => b.rating - a.rating).slice(0, 10)

// Get countries with best healthcare
export const BEST_HEALTHCARE_COUNTRIES = [...COUNTRIES_DATA]
  .sort((a, b) => (b.services?.healthcare || 0) - (a.services?.healthcare || 0))
  .slice(0, 10)

// Get countries with best education
export const BEST_EDUCATION_COUNTRIES = [...COUNTRIES_DATA]
  .sort((a, b) => (b.services?.education || 0) - (a.services?.education || 0))
  .slice(0, 10)

// Get countries with best transportation
export const BEST_TRANSPORTATION_COUNTRIES = [...COUNTRIES_DATA]
  .sort((a, b) => (b.services?.transportation || 0) - (a.services?.transportation || 0))
  .slice(0, 10)
