"""update_models_with_uuid

Revision ID: 603dc0dad552
Revises: 99a0fb77e7b6
Create Date: 2025-06-01 17:15:42.831671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app.models.utils import UUID

# revision identifiers, used by Alembic.
revision = '603dc0dad552'
down_revision = '99a0fb77e7b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('description', sa.Text(length=1000), nullable=True))
    op.add_column('countries', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('flag_url', sa.String(length=255), nullable=True))
    op.add_column('countries', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('countries', 'id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=False)
    op.alter_column('countries', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_region'), table_name='countries')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=False)
    op.drop_column('countries', 'region')
    op.add_column('evaluation_criteria', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('evaluation_criteria', 'id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=False)
    op.alter_column('evaluation_criteria', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('evaluation_criteria', 'weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_index(op.f('ix_evaluation_criteria_id'), table_name='evaluation_criteria')
    op.create_index(op.f('ix_evaluation_criteria_category'), 'evaluation_criteria', ['category'], unique=False)
    op.create_index(op.f('ix_evaluation_criteria_name'), 'evaluation_criteria', ['name'], unique=False)
    op.alter_column('evaluation_criteria_scores', 'id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=False)
    op.alter_column('evaluation_criteria_scores', 'evaluation_id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               nullable=False)
    op.alter_column('evaluation_criteria_scores', 'criteria_id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               nullable=False)
    op.drop_index(op.f('ix_evaluation_criteria_scores_id'), table_name='evaluation_criteria_scores')
    op.create_foreign_key(None, 'evaluation_criteria_scores', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluation_criteria_scores', 'evaluation_criteria', ['criteria_id'], ['id'], ondelete='CASCADE')
    op.add_column('evaluation_reports', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('evaluation_reports', 'id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=False)
    op.alter_column('evaluation_reports', 'evaluation_id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               nullable=False)
    op.alter_column('evaluation_reports', 'reporter_id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=True)
    op.alter_column('evaluation_reports', 'reason',
               existing_type=mysql.ENUM('INAPPROPRIATE', 'SPAM', 'OFFENSIVE', 'MISLEADING', 'OTHER', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('evaluation_reports', 'resolved',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_index(op.f('ix_evaluation_reports_id'), table_name='evaluation_reports')
    op.create_foreign_key(None, 'evaluation_reports', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluation_reports', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')
    op.drop_column('evaluation_reports', 'timestamp')
    op.add_column('evaluation_votes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('evaluation_votes', 'id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=False)
    op.alter_column('evaluation_votes', 'evaluation_id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               nullable=False)
    op.alter_column('evaluation_votes', 'voter_id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=True)
    op.drop_index(op.f('ix_evaluation_votes_id'), table_name='evaluation_votes')
    op.create_foreign_key(None, 'evaluation_votes', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluation_votes', 'users', ['voter_id'], ['id'], ondelete='SET NULL')
    op.drop_column('evaluation_votes', 'timestamp')
    op.add_column('evaluations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('evaluations', 'id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=False)
    op.alter_column('evaluations', 'user_id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               nullable=False)
    op.alter_column('evaluations', 'service_id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               nullable=False)
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.create_foreign_key(None, 'evaluations', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('evaluations', 'status')
    op.drop_column('evaluations', 'score')
    op.drop_column('evaluations', 'timestamp')
    op.drop_column('evaluations', 'comment')
    op.add_column('services', sa.Column('description', sa.Text(length=1000), nullable=True))
    op.add_column('services', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('services', 'id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=False)
    op.alter_column('services', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('services', 'country_id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               nullable=False)
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.create_foreign_key(None, 'services', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    op.drop_column('services', 'rating')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               type_=UUID(length=36),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('admin', 'user', name='userrole'),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'user', name='userrole'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'full_name')
    op.add_column('services', sa.Column('rating', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.alter_column('services', 'country_id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               nullable=True)
    op.alter_column('services', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191),
               nullable=True)
    op.alter_column('services', 'id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('services', 'created_at')
    op.drop_column('services', 'longitude')
    op.drop_column('services', 'latitude')
    op.drop_column('services', 'image_url')
    op.drop_column('services', 'description')
    op.add_column('evaluations', sa.Column('comment', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('evaluations', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.add_column('evaluations', sa.Column('score', mysql.FLOAT(), nullable=True))
    op.add_column('evaluations', sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED', collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.alter_column('evaluations', 'service_id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               nullable=True)
    op.alter_column('evaluations', 'user_id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               nullable=True)
    op.alter_column('evaluations', 'id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('evaluations', 'created_at')
    op.add_column('evaluation_votes', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'evaluation_votes', type_='foreignkey')
    op.drop_constraint(None, 'evaluation_votes', type_='foreignkey')
    op.create_index(op.f('ix_evaluation_votes_id'), 'evaluation_votes', ['id'], unique=False)
    op.alter_column('evaluation_votes', 'voter_id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('evaluation_votes', 'evaluation_id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               nullable=True)
    op.alter_column('evaluation_votes', 'id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('evaluation_votes', 'created_at')
    op.add_column('evaluation_reports', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'evaluation_reports', type_='foreignkey')
    op.drop_constraint(None, 'evaluation_reports', type_='foreignkey')
    op.create_index(op.f('ix_evaluation_reports_id'), 'evaluation_reports', ['id'], unique=False)
    op.alter_column('evaluation_reports', 'resolved',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('evaluation_reports', 'reason',
               existing_type=mysql.ENUM('INAPPROPRIATE', 'SPAM', 'OFFENSIVE', 'MISLEADING', 'OTHER', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('evaluation_reports', 'reporter_id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('evaluation_reports', 'evaluation_id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               nullable=True)
    op.alter_column('evaluation_reports', 'id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('evaluation_reports', 'created_at')
    op.drop_constraint(None, 'evaluation_criteria_scores', type_='foreignkey')
    op.drop_constraint(None, 'evaluation_criteria_scores', type_='foreignkey')
    op.create_index(op.f('ix_evaluation_criteria_scores_id'), 'evaluation_criteria_scores', ['id'], unique=False)
    op.alter_column('evaluation_criteria_scores', 'criteria_id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               nullable=True)
    op.alter_column('evaluation_criteria_scores', 'evaluation_id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               nullable=True)
    op.alter_column('evaluation_criteria_scores', 'id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_evaluation_criteria_name'), table_name='evaluation_criteria')
    op.drop_index(op.f('ix_evaluation_criteria_category'), table_name='evaluation_criteria')
    op.create_index(op.f('ix_evaluation_criteria_id'), 'evaluation_criteria', ['id'], unique=False)
    op.alter_column('evaluation_criteria', 'weight',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('evaluation_criteria', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('evaluation_criteria', 'id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('evaluation_criteria', 'created_at')
    op.add_column('countries', sa.Column('region', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_index(op.f('ix_countries_region'), 'countries', ['region'], unique=False)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.alter_column('countries', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('countries', 'id',
               existing_type=UUID(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('countries', 'created_at')
    op.drop_column('countries', 'flag_url')
    op.drop_column('countries', 'longitude')
    op.drop_column('countries', 'latitude')
    op.drop_column('countries', 'description')
    # ### end Alembic commands ###
